services:
  # Backend - FastAPI ML Service
  - type: web
    name: ttc-delay-backend
    env: python
    region: oregon
    buildCommand: |
      cd machineLearning
      pip install -r requirements.txt
    startCommand: |
      cd machineLearning
      python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: 8000
    healthCheckPath: /health
    autoDeploy: true
    disk:
      name: model-data
      mountPath: /app/machineLearning
      sizeGB: 1

  # Frontend - React App
  - type: web
    name: ttc-delay-frontend
    env: static
    region: oregon
    buildCommand: |
      cd frontend
      npm install
      npm run build
    staticPublishPath: frontend/dist
    headers:
      - path: /*
        name: X-Frame-Options
        value: SAMEORIGIN
      - path: /*
        name: X-Content-Type-Options
        value: nosniff
      - path: /assets/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    envVars:
      - key: NODE_VERSION
        value: 18.19.0
      - key: VITE_API_BASE_URL
        fromService:
          type: web
          name: ttc-delay-backend
          property: host
    autoDeploy: true
